[lldb][test] Disable a bunch of flakey lldb-dap tests
These, or parts of these, are all failing every so often on Linaro's
build bots with:
    raise ValueError(desc)
ValueError: no response for "disconnect"

Sorry to use a global disable here but this is happening too often
and spamming unrelated PRs.

I think it's the same issue as https://github.com/llvm/llvm-project/issues/137660.

(cherry picked from commit 2dbab4ca8ddb218af555d8d1fd86b72612387582)